name: "Keep the witnesses repository active!"

on:
  # Run Thursday at 02:23 every week
  schedule:
    - cron: '23 2 * * THU'
  # Allow manual execution
  workflow_dispatch:

jobs:
  keep-repo-active:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup gitHub User Details
        uses: octoleo/git-user@v2
        with:
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-user: ${{ secrets.GPG_USER }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-pub: ${{ secrets.SSH_PUB }}
          git-user: ${{ secrets.GIT_USER }}
          git-email: ${{ secrets.GIT_EMAIL }}

      - name: Clone Master Repository
        run: git clone git@github.com:trueChristian/witnesses.git witnesses

      - name: Set Repository Active
        run: |
          cd witnesses
          ./src/active.sh

