name: "Testing all Telegram out!"

on:
  # Allow manual run only
  workflow_dispatch:

jobs:
  test-all-telegram:
    runs-on: ubuntu-22.04

    steps:
      - name: Show Python Version
        run: python3 --version

      - name: Install Python Dependencies
        run: |
          sudo python3 -m pip install --upgrade pip
          sudo pip3 install telegram-send==0.25 python-telegram-bot==13.5

      - name: Setup gitHub User Details
        uses: octoleo/git-user@v2
        with:
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-user: ${{ secrets.GPG_USER }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-pub: ${{ secrets.SSH_PUB }}
          git-user: ${{ secrets.GIT_USER }}
          git-email: ${{ secrets.GIT_EMAIL }}

      - name: Clone Master Repository
        run: git clone git@github.com:trueChristian/witnesses.git witnesses

      - name: Send All Daily Messages To Telegram (Test Bot)
        env:
          BOT_CONF: ${{ secrets.TG_TEST_BOT_CONF }}
        run: |
          cd witnesses
          ./src/telegram.sh --bot-conf "$BOT_CONF" \
            --message-url "https://raw.githubusercontent.com/trueChristian/daily-scripture/master/README.tg" \
            --format html
          ./src/telegram.sh --bot-conf "$BOT_CONF" \
            --message-url "https://raw.githubusercontent.com/trueChristian/daily-light/master/morning.html" \
            --format html
          ./src/telegram.sh --bot-conf "$BOT_CONF" \
            --message-url "https://raw.githubusercontent.com/trueChristian/daily-light/master/evening.html" \
            --format html

